name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.22.x

      - name: Install Kafka
        run: |
          wget --progress=dot:giga https://dlcdn.apache.org/kafka/3.8.0/kafka_2.13-3.8.0.tgz
          tar -xzf kafka_2.13-3.8.0.tgz
          sudo mv kafka_2.13-3.8.0/ /usr/local/kafka
          export PATH=$PATH:/usr/local/kafka/bin

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - run: make test
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.22.x

      - uses: dominikh/staticcheck-action@v1.3.1
        with:
          version: "2024.1"
          install-go: false