name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.22.x

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - run: make test
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.22.x

      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1"
          install-go: false