name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.22.x

      - name: Fetch latest release of Kafka && extract it
        run: |
          wget --progress=dot:giga https://media.githubusercontent.com/media/codecrafters-io/build-your-own-kafka/main/kafka_2.13-4.0.0-SNAPSHOT.tgz
          tar -xzf kafka_2.13-4.0.0-SNAPSHOT.tgz
          sudo mv kafka_2.13-4.0.0-SNAPSHOT/ /usr/local/kafka-latest
          export PATH=$PATH:/usr/local/kafka-latest/bin

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'

      - run: make test
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.22.x

      - uses: dominikh/staticcheck-action@v1.3.1
        with:
          version: "2024.1"
          install-go: false